version: '3'
services:
  node:
    build: .
    restart: always
    container_name: node
    ports:
      - 3000:3999
    links:
      - db
    volumes:
      - ./:/code
  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    #env_file: 
     # - production.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root #${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: root #${MONGO_PASSWORD}
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: